### ISSUE TITLE
Changelog Says Download Link by Mistake

### ISSUE THREAD

**Issue by minekraftminer** [DerToaster98/cq-repoured-website#1]
**Describe the bug**
On The Downloads tab of the new website, the text above the changelog says Download Link

**To Reproduce**

**Screenshots**
![image](https://github.com/DerToaster98/cq-repoured-website/assets/82829316/a24364fe-7711-4f32-bb5f-858da8fa89dc)

**Comment by DerToaster98** [comment]
Fixed
